import { Governorate, Institution, Post, Opportunity, Notification } from './types';

export const GOVERNORATES: Governorate[] = [
  'بغداد', 'البصرة', 'الموصل', 'أربيل', 'السليمانية', 'دهوك',
  'النجف', 'كربلاء', 'الأنبار', 'ديالى', 'كركوك', 'واسط',
  'المثنى', 'ذي قار', 'ميسان', 'بابل', 'صلاح الدين', 'القادسية'
];

export const SAMPLE_INSTITUTIONS: Institution[] = [
  {
    id: '1',
    name: 'جامعة بغداد',
    nameEn: 'University of Baghdad',
    type: 'university',
    isPublic: true,
    governorate: 'بغداد',
    city: 'بغداد - الجادرية',
    logo: 'https://picsum.photos/seed/uob_logo/100/100',
    cover: 'https://picsum.photos/seed/uob_cover/800/400',
    students: 50000,
    followers: 120000,
    postCount: 3400,
    description: 'الأم والجامعة العريقة في قلب العاصمة بغداد.'
  },
  {
    id: '2',
    name: 'الجامعة المستنصرية',
    nameEn: 'Mustansiriyah University',
    type: 'university',
    isPublic: true,
    governorate: 'بغداد',
    city: 'بغداد - الرصافة',
    logo: 'https://picsum.photos/seed/must/100/100',
    cover: 'https://picsum.photos/seed/must_cover/800/400',
    students: 45000,
    followers: 95000,
    postCount: 2800,
    description: 'صرح علمي شامخ ومعلم من معالم بغداد التاريخية.'
  },
  {
    id: '3',
    name: 'جامعة الموصل',
    nameEn: 'University of Mosul',
    type: 'university',
    isPublic: true,
    governorate: 'الموصل',
    city: 'الموصل',
    logo: 'https://picsum.photos/seed/mosul/100/100',
    cover: 'https://picsum.photos/seed/mosul_cover/800/400',
    students: 35000,
    followers: 80000,
    postCount: 1500,
    description: 'مركز العلم والثقافة في نينوى الحدباء.'
  },
  {
    id: '4',
    name: 'جامعة البصرة',
    nameEn: 'University of Basrah',
    type: 'university',
    isPublic: true,
    governorate: 'البصرة',
    city: 'البصرة',
    logo: 'https://picsum.photos/seed/basrah/100/100',
    cover: 'https://picsum.photos/seed/basrah_cover/800/400',
    students: 30000,
    followers: 70000,
    postCount: 2200,
    description: 'بوابة العراق البحرية ومنار العلم في الجنوب.'
  },
  {
    id: '5',
    name: 'جامعة النهرين',
    nameEn: 'Al-Nahrain University',
    type: 'university',
    isPublic: true,
    governorate: 'بغداد',
    city: 'بغداد - الجادرية',
    logo: 'https://picsum.photos/seed/nahrain/100/100',
    cover: 'https://picsum.photos/seed/nahrain_cover/800/400',
    students: 15000,
    followers: 45000,
    postCount: 900,
    description: 'التميز العلمي والبحثي في خدمة المجتمع.'
  },
  {
    id: '6',
    name: 'كلية الرشيد الجامعة',
    nameEn: 'Al-Rasheed University College',
    type: 'college',
    isPublic: false,
    governorate: 'بغداد',
    city: 'بغداد',
    logo: 'https://picsum.photos/seed/rasheed/100/100',
    cover: 'https://picsum.photos/seed/rasheed_cover/800/400',
    students: 8000,
    followers: 25000,
    postCount: 450,
    description: 'من أعرق الكليات الأهلية في العراق.'
  },
  {
    id: '7',
    name: 'جامعة بابل',
    nameEn: 'University of Babylon',
    type: 'university',
    isPublic: true,
    governorate: 'بابل',
    city: 'الحلة',
    logo: 'https://picsum.photos/seed/babil/100/100',
    cover: 'https://picsum.photos/seed/babil_cover/800/400',
    students: 28000,
    followers: 60000,
    postCount: 1100,
    description: 'صرح العلم في أرض الحضارات.'
  },
  {
    id: '8',
    name: 'جامعة كربلاء',
    nameEn: 'University of Kerbala',
    type: 'university',
    isPublic: true,
    governorate: 'كربلاء',
    city: 'كربلاء المقدسة',
    logo: 'https://picsum.photos/seed/karbala/100/100',
    cover: 'https://picsum.photos/seed/karbala_cover/800/400',
    students: 22000,
    followers: 55000,
    postCount: 950,
    description: 'المنهل العلمي والفكري في مدينة الحسين.'
  },
  {
    id: '9',
    name: 'جامعة الكوفة',
    nameEn: 'University of Kufa',
    type: 'university',
    isPublic: true,
    governorate: 'النجف',
    city: 'النجف الأشرف',
    logo: 'https://picsum.photos/seed/kufa/100/100',
    cover: 'https://picsum.photos/seed/kufa_cover/800/400',
    students: 32000,
    followers: 75000,
    postCount: 1800,
    description: 'امتداد لعمق العلم والتاريخ في كوفة العرب.'
  },
  {
    id: '10',
    name: 'جامعة صلاح الدين',
    nameEn: 'Salahaddin University-Erbil',
    type: 'university',
    isPublic: true,
    governorate: 'أربيل',
    city: 'أربيل',
    logo: 'https://picsum.photos/seed/salah/100/100',
    cover: 'https://picsum.photos/seed/salah_cover/800/400',
    students: 25000,
    followers: 90000,
    postCount: 1400,
    description: 'أقدم وأكبر جامعة حكومية في إقليم كردستان.'
  },
  {
    id: '11',
    name: 'جامعة السليمانية',
    nameEn: 'University of Sulaimani',
    type: 'university',
    isPublic: true,
    governorate: 'السليمانية',
    city: 'السليمانية',
    logo: 'https://picsum.photos/seed/sul/100/100',
    cover: 'https://picsum.photos/seed/sul_cover/800/400',
    students: 23000,
    followers: 85000,
    postCount: 1200,
    description: 'منارة العلم والثقافة في مدينة السليمانية.'
  },
  {
    id: '12',
    name: 'جامعة دهوك',
    nameEn: 'University of Duhok',
    type: 'university',
    isPublic: true,
    governorate: 'دهوك',
    city: 'دهوك',
    logo: 'https://picsum.photos/seed/duhok/100/100',
    cover: 'https://picsum.photos/seed/duhok_cover/800/400',
    students: 18000,
    followers: 65000,
    postCount: 880,
    description: 'مؤسسة أكاديمية رائدة في شمال العراق.'
  },
  {
    id: '13',
    name: 'جامعة ذي قار',
    nameEn: 'University of Thi-Qar',
    type: 'university',
    isPublic: true,
    governorate: 'ذي قار',
    city: 'الناصرية',
    logo: 'https://picsum.photos/seed/thiqar/100/100',
    cover: 'https://picsum.photos/seed/thiqar_cover/800/400',
    students: 20000,
    followers: 40000,
    postCount: 750,
    description: 'صوت العلم من بلاد سومر.'
  },
  {
    id: '14',
    name: 'جامعة ميسان',
    nameEn: 'University of Misan',
    type: 'university',
    isPublic: true,
    governorate: 'ميسان',
    city: 'العمارة',
    logo: 'https://picsum.photos/seed/misan/100/100',
    cover: 'https://picsum.photos/seed/misan_cover/800/400',
    students: 12000,
    followers: 30000,
    postCount: 420,
    description: 'منار المعرفة في مدينة الأهوار.'
  },
  {
    id: '15',
    name: 'جامعة القادسية',
    nameEn: 'University of Al-Qadisiyah',
    type: 'university',
    isPublic: true,
    governorate: 'القادسية',
    city: 'الديوانية',
    logo: 'https://picsum.photos/seed/qad/100/100',
    cover: 'https://picsum.photos/seed/qad_cover/800/400',
    students: 19000,
    followers: 38000,
    postCount: 560,
    description: 'التميز الأكاديمي في قلب الفرات الأوسط.'
  },
  {
    id: '16',
    name: 'جامعة الأنبار',
    nameEn: 'University of Anbar',
    type: 'university',
    isPublic: true,
    governorate: 'الأنبار',
    city: 'الرمادي',
    logo: 'https://picsum.photos/seed/anbar/100/100',
    cover: 'https://picsum.photos/seed/anbar_cover/800/400',
    students: 24000,
    followers: 72000,
    postCount: 1300,
    description: 'الإرادة والعلم في محافظة الأنبار العزيزة.'
  },
  {
    id: '17',
    name: 'جامعة ديالى',
    nameEn: 'University of Diyala',
    type: 'university',
    isPublic: true,
    governorate: 'ديالى',
    city: 'بعقوبة',
    logo: 'https://picsum.photos/seed/diyala/100/100',
    cover: 'https://picsum.photos/seed/diyala_cover/800/400',
    students: 17000,
    followers: 44000,
    postCount: 680,
    description: 'صرح العلم في محافظة البرتقال.'
  },
  {
    id: '18',
    name: 'جامعة كركوك',
    nameEn: 'University of Kirkuk',
    type: 'university',
    isPublic: true,
    governorate: 'كركوك',
    city: 'كركوك',
    logo: 'https://picsum.photos/seed/kirkuk/100/100',
    cover: 'https://picsum.photos/seed/kirkuk_cover/800/400',
    students: 21000,
    followers: 58000,
    postCount: 920,
    description: 'جامعة التآخي والتعايش السلمي.'
  },
  {
    id: '19',
    name: 'جامعة واسط',
    nameEn: 'University of Wasit',
    type: 'university',
    isPublic: true,
    governorate: 'واسط',
    city: 'الكوت',
    logo: 'https://picsum.photos/seed/wasit/100/100',
    cover: 'https://picsum.photos/seed/wasit_cover/800/400',
    students: 16000,
    followers: 35000,
    postCount: 510,
    description: 'الواحة العلمية في واسط الخير.'
  },
  {
    id: '20',
    name: 'جامعة المثنى',
    nameEn: 'Al-Muthanna University',
    type: 'university',
    isPublic: true,
    governorate: 'المثنى',
    city: 'السماوة',
    logo: 'https://picsum.photos/seed/muthanna/100/100',
    cover: 'https://picsum.photos/seed/muthanna_cover/800/400',
    students: 11000,
    followers: 28000,
    postCount: 390,
    description: 'العلم والمعرفة في ربوع السماوة.'
  },
  {
    id: '21',
    name: 'جامعة تكريت',
    nameEn: 'University of Tikrit',
    type: 'university',
    isPublic: true,
    governorate: 'صلاح الدين',
    city: 'تكريت',
    logo: 'https://picsum.photos/seed/tikrit/100/100',
    cover: 'https://picsum.photos/seed/tikrit_cover/800/400',
    students: 22000,
    followers: 52000,
    postCount: 840,
    description: 'مؤسسة تعليمية رائدة في محافظة صلاح الدين.'
  },
  {
    id: '22',
    name: 'الجامعة التقنية الجنوبية',
    nameEn: 'Southern Technical University',
    type: 'university',
    isPublic: true,
    governorate: 'البصرة',
    city: 'البصرة',
    logo: 'https://picsum.photos/seed/stu/100/100',
    cover: 'https://picsum.photos/seed/stu_cover/800/400',
    students: 14000,
    followers: 32000,
    postCount: 600,
    description: 'التعليم التقني والابتكار في خدمة التنمية.'
  },
  {
    id: '23',
    name: 'جامعة بابل للدراسات الإنسانية',
    nameEn: 'Al-Hilla University College',
    type: 'college',
    isPublic: false,
    governorate: 'بابل',
    city: 'الحلة',
    logo: 'https://picsum.photos/seed/hilla/100/100',
    cover: 'https://picsum.photos/seed/hilla_cover/800/400',
    students: 5000,
    followers: 12000,
    postCount: 210,
    description: 'منارة العلم الأهلية في بابل.'
  }
];

export const SAMPLE_POSTS: Post[] = [
  {
    id: 'p1',
    type: 'announcement',
    title: 'بدء التقديم للدراسات العليا',
    institutionName: 'جامعة بغداد',
    institutionLogo: 'https://picsum.photos/seed/uob_logo/100/100',
    governorate: 'بغداد',
    content: 'تعلن رئاسة جامعة بغداد عن بدء التقديم للدراسات العليا للعام الدراسي القادم. يشمل التقديم كافة التخصصات العلمية والإنسانية وفق الضوابط المعلنة.',
    image: 'https://picsum.photos/seed/post1/800/500',
    likes: 1240,
    comments: 89,
    views: 5600,
    timestamp: 'منذ ساعتين',
    isVerified: true
  },
  {
    id: 'p-urgent',
    type: 'urgent',
    title: 'تأجيل الامتحانات النهائية',
    institutionName: 'الجامعة المستنصرية',
    institutionLogo: 'https://picsum.photos/seed/must/100/100',
    governorate: 'بغداد',
    content: 'تقرر تأجيل امتحانات يوم غد الخميس نظراً لسوء الأحوال الجوية المتوقعة. يرجى متابعة الجداول المحدثة لاحقاً.',
    likes: 4500,
    comments: 1200,
    views: 15400,
    timestamp: 'منذ ١٠ دقائق',
    isVerified: true
  },
  {
    id: 'p2',
    type: 'event',
    title: 'مهرجان الابتكار الرقمي ٢٠٢٤',
    institutionName: 'الجامعة المستنصرية',
    institutionLogo: 'https://picsum.photos/seed/must/100/100',
    governorate: 'بغداد',
    content: 'ندعوكم لحضور المهرجان السنوي للابتكار والذكاء الاصطناعي في القاعة الكبرى. جوائز قيمة للمشاريع المتميزة.',
    image: 'https://picsum.photos/seed/post2/800/500',
    likes: 856,
    comments: 45,
    eventDate: { day: '٢٤', month: 'مايو' },
    timestamp: 'منذ 5 ساعات',
    isVerified: true
  },
  {
    id: 'p3',
    type: 'student',
    authorName: 'أحمد علي',
    authorAvatar: 'https://picsum.photos/seed/student1/100/100',
    institutionName: 'جامعة الموصل',
    institutionLogo: 'https://picsum.photos/seed/mosul/100/100',
    governorate: 'الموصل',
    content: 'أجواء دراسية رائعة اليوم في مكتبة الجامعة. بالتوفيق للجميع في الامتحانات النهائية!',
    image: 'https://picsum.photos/seed/student_post/800/500',
    likes: 320,
    comments: 12,
    timestamp: 'منذ 8 ساعات'
  },
  {
    id: 'o-job',
    type: 'opportunity',
    title: 'مطور واجهات برمجية (React)',
    institutionName: 'شركة بوابة العراق',
    institutionLogo: 'https://picsum.photos/seed/iq-gate/100/100',
    governorate: 'بغداد',
    content: 'نبحث عن مطور ذكي شغوف لتعزيز فريقنا التقني. خبرة عام على الأقل في React و Tailwind.',
    deadline: '١٥ حزيران',
    tags: ['برمجة', 'بغداد', 'وظيفة'],
    likes: 450,
    comments: 23,
    timestamp: 'منذ يوم'
  },
  {
    id: 'p4',
    type: 'announcement',
    title: 'توسع القبول في المجموعة الطبية',
    institutionName: 'جامعة الكوفة',
    institutionLogo: 'https://picsum.photos/seed/kufa/100/100',
    governorate: 'النجف',
    content: 'تعلن وزارة التعليم العالي عن موافقتها على زيادة خطة القبول في كليات الطب وطب الأسنان في جامعة الكوفة لهذا العام الدراسي استجابة للحاجة المحلية.',
    likes: 890,
    comments: 120,
    views: 4500,
    timestamp: 'منذ ١٢ ساعة',
    isVerified: true
  },
  {
    id: 'p5',
    type: 'event',
    title: 'أسبوع ريادة الأعمال في البصرة',
    institutionName: 'الجامعة التقنية الجنوبية',
    institutionLogo: 'https://picsum.photos/seed/stu/100/100',
    governorate: 'البصرة',
    content: 'ورش عمل وجلسات حوارية لمساعدة الطلبة على بدء مشاريعهم الناشئة. حضور مميز لنخبة من رواد الأعمال في المحافظة.',
    image: 'https://picsum.photos/seed/basra_event/800/500',
    likes: 560,
    comments: 34,
    eventDate: { day: '٠٥', month: 'يونيو' },
    timestamp: 'منذ يوم',
    isVerified: true
  },
  {
    id: 'p6',
    type: 'student',
    authorName: 'سارة محمد',
    authorAvatar: 'https://picsum.photos/seed/student2/100/100',
    institutionName: 'جامعة بابل',
    institutionLogo: 'https://picsum.photos/seed/babil/100/100',
    governorate: 'بابل',
    content: 'مشروع تخرجي اليوم في كلية الهندسة - جامعة بابل. فخورة جداً بهذا الإنجاز وشكراً لكل من ساندني!',
    image: 'https://picsum.photos/seed/grad_post/800/500',
    likes: 980,
    comments: 78,
    timestamp: 'منذ ١٨ ساعة'
  }
];

export const SAMPLE_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'o1',
    title: 'مهندس برمجيات متدرب',
    type: 'internship',
    institutionName: 'شركة زين العراق',
    institutionLogo: 'https://picsum.photos/seed/zain/100/100',
    governorate: 'بغداد',
    deadline: '2024-06-15',
    tags: ['Tech', 'Baghdad', 'Intern']
  },
  {
    id: 'o2',
    title: 'منحة دراسية لدراسة الماجستير',
    type: 'scholarship',
    institutionName: 'رئاسة الوزراء - البعثات',
    institutionLogo: 'https://picsum.photos/seed/gov/100/100',
    governorate: 'بغداد',
    deadline: '2024-07-01',
    tags: ['Master', 'International', 'Scholarship']
  },
  {
    id: 'o3',
    title: 'محلل بيانات ناشئ',
    type: 'job',
    institutionName: 'مصرف الرافدين',
    institutionLogo: 'https://picsum.photos/seed/rafidain/100/100',
    governorate: 'بغداد',
    deadline: '2024-06-20',
    tags: ['Finance', 'Data', 'Full-time']
  },
  {
    id: 'o4',
    title: 'تدريب مهني في حقول النفط',
    type: 'training',
    institutionName: 'شركة نفط البصرة',
    institutionLogo: 'https://picsum.photos/seed/oil/100/100',
    governorate: 'البصرة',
    deadline: '2024-07-15',
    tags: ['Energy', 'Engineering', 'Training']
  }
];

export const SAMPLE_INSIGHTS: Post[] = [
  {
    id: 'ins1',
    type: 'insight',
    title: 'أكثر المهارات المطلوبة في سوق العمل العراقي ٢٠٢٤',
    institutionName: 'جامعة بغداد - مركز المهنة',
    institutionLogo: 'https://picsum.photos/seed/uob_logo/100/100',
    governorate: 'بغداد',
    content: 'أظهرت دراسة حديثة أجراها مركز تطوير المهارات في جامعة بغداد أن المهارات التقنية والتحليلية تتصدر قائمة الطلب لدى الشركات المحلية والدولية العاملة في العراق.',
    likes: 2450,
    comments: 156,
    views: 8900,
    timestamp: 'منذ يومين',
    isVerified: true,
    chartData: [
      { name: 'برمجة', value: 85 },
      { name: 'تحليل', value: 65 },
      { name: 'تسويق', value: 45 },
      { name: 'إدارة', value: 70 },
      { name: 'لغات', value: 50 }
    ]
  },
  {
    id: 'ins2',
    type: 'insight',
    title: 'توزيع الخريجين حسب التخصصات والتوظيف',
    institutionName: 'وزارة التعليم العالي والبحث العلمي',
    institutionLogo: 'https://picsum.photos/seed/mohe/100/100',
    governorate: 'بغداد',
    content: 'تقرير تفصيلي حول نسب توظيف الخريجين الجدد في القطاعين العام والخاص، مع تسليط الضوء على الفجوة بين التعليم الأكاديمي واحتياجات السوق.',
    likes: 1890,
    comments: 234,
    views: 12000,
    timestamp: 'منذ أسبوع',
    isVerified: true,
    chartData: [
      { name: 'هندسة', value: 40 },
      { name: 'طب', value: 95 },
      { name: 'علوم', value: 30 },
      { name: 'إدارة', value: 55 },
      { name: 'آداب', value: 25 }
    ]
  }
];

export const SAMPLE_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'social',
    subType: 'like',
    title: 'أعجب علي ببروفايلك',
    content: 'قام علي محمد بالإعجاب بصورتك الشخصية الجديدة.',
    timestamp: 'منذ ٥ دقائق',
    group: 'today',
    isRead: false,
    avatar: 'https://picsum.photos/seed/n1/100/100'
  },
  {
    id: 'n2',
    type: 'opportunity',
    subType: 'system',
    title: 'فرصة عمل جديدة',
    content: 'توجد فرصة تدريب جديدة في جامعة بغداد تناسب اهتماماتك.',
    timestamp: 'منذ ساعتين',
    group: 'today',
    isRead: false
  },
  {
    id: 'n3',
    type: 'announcement',
    subType: 'urgent',
    title: 'تنبيه عاجل من الجامعة',
    content: 'تم تأجيل موعد تسليم طلبات الدراسات العليا ليومين إضافيين.',
    timestamp: 'منذ ٤ ساعات',
    group: 'today',
    isRead: true
  },
  {
    id: 'n4',
    type: 'event',
    subType: 'system',
    title: 'فعالية قادمة غداً',
    content: 'لا تنسَ حضور مؤتمر الذكاء الاصطناعي في القاعة الكبرى.',
    timestamp: 'منذ يوم',
    group: 'this_week',
    isRead: true
  },
  {
    id: 'n5',
    type: 'social',
    subType: 'follow',
    title: 'متابع جديد',
    content: 'بدأ سيف أحمد بمتابعتك الآن.',
    timestamp: 'منذ يومين',
    group: 'this_week',
    isRead: true,
    avatar: 'https://picsum.photos/seed/n5/100/100'
  }
];
